import { prisma } from "../src/db/prisma";
import { sendEmailBestEffort } from "../src/shared/email";
import {
  createNotification,
  getUserNotifications,
  markNotificationAsRead,
  markAllNotificationsAsRead,
} from "../src/modules/notifications/notification.service";

async function runTests() {
  console.log("=== Starting Infrastructure Tests ===\n");

  // 1. Get a test user from the DB
  const user = await prisma.user.findFirst();
  if (!user) {
    console.error("No users found in the database. Please seed the database first.");
    process.exit(1);
  }

  console.log(`Using test user: ${user.email} (ID: ${user.id})\n`);

  // 2. Test Email Sending
  console.log("--- Testing Email Service ---");
  try {
    await sendEmailBestEffort({
      to: ["shaamidreez@gmail.com"], // Sent to requested email
      subject: "Gaza40+ Infrastructure Test",
      text: "This is a plain text test.",
      html: "<strong>This is an HTML test from the new email abstraction layer!</strong>",
    });
    console.log("✅ Email queued successfully (check server console logs for SMTP/Resend status).\n");
  } catch (e: any) {
    console.error("❌ Email test failed:", e.message);
  }

  // 3. Test Notification Creation
  console.log("--- Testing Notification Creation ---");
  const newNotif = await createNotification({
    userId: user.id,
    type: "test_notification",
    title: "Test Notification",
    body: "This is a test notification generated by the infrastructure script.",
    link: "/dashboard",
  });
  console.log(`✅ Notification created (ID: ${newNotif.id})\n`);

  // 4. Test Notification Retrieval
  console.log("--- Testing Notification Retrieval ---");
  const { notifications, totalUnread } = await getUserNotifications(user.id);
  console.log(`✅ Retrieved ${notifications.length} notifications. Unread count: ${totalUnread}\n`);

  // 5. Test Mark as Read
  console.log("--- Testing Mark as Read ---");
  await markNotificationAsRead(user.id, newNotif.id);
  
  // Verify it was read
  const { totalUnread: unreadAfterMark } = await getUserNotifications(user.id);
  console.log(`✅ Marked notification as read. New unread count: ${unreadAfterMark}\n`);

  // 6. Test Mark All as Read
  console.log("--- Testing Mark All as Read ---");
  await markAllNotificationsAsRead(user.id);
  const { totalUnread: finalUnread } = await getUserNotifications(user.id);
  console.log(`✅ Marked all as read. Final unread count: ${finalUnread}\n`);

  console.log("=== All Tests Completed ===");
}

runTests()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
